# Generated by Django 5.1.6 on 2025-03-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='groups',
        ),
    ]
