# Generated by Django 5.1.6 on 2025-04-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_student_mails_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.ManyToManyField(to='children.homework'),
        ),
    ]
