# Generated by Django 5.1.6 on 2025-04-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_lesson_homework'),
        ('parent', '0002_alter_parents_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='group_lessons',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='group_lessons',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Behavior',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Group_Lessons',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
