# Generated by Django 5.1.6 on 2025-04-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_remove_student_behavior_remove_grade_lesson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
