# Generated by Django 5.1.6 on 2025-04-12 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_behavior_grade_student_group_students'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
    ]
