# Generated by Django 5.1.6 on 2025-03-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_group_teacher_remove_student_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
