# Generated by Django 5.1.6 on 2025-03-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_break_schedule_lesson_remove_student_grades_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_mails',
        ),
    ]
