# Generated by Django 5.1.6 on 2025-04-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_behavior_grade_student_group_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
    ]
