# Generated by Django 5.1.6 on 2025-04-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_group_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='homework',
            field=models.ManyToManyField(to='base.homework'),
        ),
    ]
