# Generated by Django 5.1.6 on 2025-04-13 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_homework_group_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='homework',
        ),
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.group'),
        ),
    ]
