# Generated by Django 5.1.6 on 2025-04-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_group_homework_homework_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='homework',
            field=models.ManyToManyField(to='base.homework'),
        ),
    ]
