# Generated by Django 5.1.6 on 2025-04-27 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_homework_group_group_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='Homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.homework'),
        ),
        migrations.AddField(
            model_name='homework',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
