# Generated by Django 5.1.6 on 2025-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_grade_homework_homework_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='solve',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='solve_files',
            field=models.FileField(null=True, upload_to='homework'),
        ),
    ]
