# Generated by Django 5.1.6 on 2025-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_homework_solve_homework_solve_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Homework',
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
