# Generated by Django 5.1.6 on 2025-05-10 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_grade_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('files', models.FileField(null=True, upload_to='homework')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.homework')),
            ],
        ),
    ]
