# Generated by Django 5.1.6 on 2025-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_studenthomework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='solve',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='solve_files',
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
