# Generated by Django 5.1.6 on 2025-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_homework_solve_remove_homework_solve_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='files',
            field=models.FileField(null=True, upload_to='static/hw_files'),
        ),
    ]
