# Generated by Django 5.1.6 on 2025-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_studenthomework_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='hw_files')),
            ],
        ),
        migrations.RemoveField(
            model_name='studenthomework',
            name='files',
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='base.homeworkfiles'),
        ),
    ]
