# Generated by Django 5.1.6 on 2025-05-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_homeworkfiles_remove_studenthomework_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthomework',
            name='homework',
        ),
        migrations.AddField(
            model_name='homework',
            name='studentHomework',
            field=models.ManyToManyField(blank=True, null=True, to='base.studenthomework'),
        ),
    ]
