# Generated by Django 5.1.6 on 2025-05-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_studenthomework_homework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='studentHomework',
            field=models.ManyToManyField(blank=True, to='base.studenthomework'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='files',
            field=models.ManyToManyField(blank=True, to='base.homeworkfiles'),
        ),
    ]
