# Generated by Django 5.1.6 on 2025-05-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_homework_studenthomework_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
    ]
