# Generated by Django 5.1.6 on 2025-05-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_studenthomework_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='state',
            field=models.CharField(default='not done', max_length=50),
        ),
    ]
