# Generated by Django 5.1.6 on 2025-05-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_grade_grade_alter_homework_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthomework',
            name='files',
        ),
        migrations.RemoveField(
            model_name='studenthomework',
            name='student',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='studentHomework',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='state',
        ),
        migrations.DeleteModel(
            name='HomeworkFiles',
        ),
        migrations.DeleteModel(
            name='StudentHomework',
        ),
    ]
