# Generated by Django 5.1.6 on 2025-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_studenthomework_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
